### ISSUE TITLE
MP3 sometimes don't reproduce when called.

### ISSUE THREAD

**Issue by Ozhaaraz** [baykovr/AVPI#59] opened 2016-08-11 18:46 UTC
This bug is easily reproducible trying to invoke a few times the same voice command which trigger an audio mp3 file.

**Comment by baykovr** [comment] 2016-08-14 23:03
Is this possibly a duplicate of #54?

**Comment by baykovr** [comment] 2016-08-27 18:25
Fixed in commit above.

**Closed by baykovr** 2016-08-27 18:25 UTC
Labels: bug
